language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-ucp' ]; then cd .. && eval "mv $currentfolder generator-ucp" && cd generator-ucp; fi

